mysql_salver_1:
  image: mysql:5.7
  ports:
  - 3306:3306
  volumes:
  - ./volumes/mysql_salver_1:/var/lib/mysql
  - './volumes/mysql_cnf_salver_1:/etc/mysql/conf.d:ro'
  environment:
    MYSQL_ROOT_PASSWORD: Hello.123

mysql_salver_2:
  image: mysql:5.7
  ports:
  - 3307:3306
  volumes:
  - ./volumes/mysql_salver_2:/var/lib/mysql
  - './volumes/mysql_cnf_salver_2:/etc/mysql/conf.d:ro'
  environment:
    MYSQL_ROOT_PASSWORD: Hello.123

mysql_salver_3:
  image: mysql:5.7
  ports:
  - 3308:3306
  volumes:
  - ./volumes/mysql_salver_3:/var/lib/mysql
  - './volumes/mysql_cnf_salver_3:/etc/mysql/conf.d:ro'
  environment:
    MYSQL_ROOT_PASSWORD: Hello.123
